version: '3.4'

services:
  postgres:
    image: postgres:13.0
    container_name: 'java-postgres'
    ports:
      - "12345:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres